version: "3"

services:
  webdav:
    build: .
    ports:
      - "127.0.0.1:18088:80"
    volumes:
      - "C:/temp:/media"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: unless-stopped
